# Generated by Django 4.1.1 on 2022-09-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminals',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
