# Generated by Django 4.1.1 on 2022-09-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_terminals_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminals',
            name='status',
        ),
    ]
